name: ratropolis_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.7.2 <4.0.0"
resolution: workspace

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  game_core:
    path: ../packages/core/game_core
  provider: ^6.1.5+1
  rp_cards_screen:
    path: ../packages/ui/screens/rp_cards_screen
  rp_city_screen:
    path: ../packages/ui/screens/rp_city_screen
  rp_game_screen:
    path: ../packages/ui/screens/rp_game_screen
  rp_heroes_screen:
    path: ../packages/ui/screens/rp_heroes_screen
  rp_shop_screen:
    path: ../packages/ui/screens/rp_shop_screen
  rp_user_screen:
    path: ../packages/ui/screens/rp_user_screen
  rp_widgets:
    path: ../packages/ui/rp_widgets

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
