name: rp_widgets
description: "Package grouping reusable widgets."
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  game_core:
    path: ../../core/game_core
  lottie: ^3.3.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
